server:
  port: 50004

spring:
  security:
    user:
      password: 213100
      name: Yama
  datasource:
    url: jdbc:mysql://localhost:3306/account?serverTimezone=GMT
    username: root
    password: 213100
    driver-class-name: com.mysql.cj.jdbc.Driver
