server:
  port: 50001
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paper?characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 213100
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
